[package]
name = "include_tt"
version = "1.0.1"
edition = "2021"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
repository = "https://github.com/clucompany/include_tt.git"
homepage = "https://crates.io/crates/include_tt"
license = "MIT/Apache-2.0"
readme = "README.md"

description = "Macro for including trees, strings, arrays from files."
keywords = ["procedural-macros", "macros", "code-generation", "code-transformation", "clucompany"]
categories = ["development-tools", "development-tools::build-utils"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.31"
proc-macro2 = "1.0.66"

[dependencies.syn]
version = "2.0.26"
features = ["full"]
